version: "3"
services:
  db:
    image: "postgres:11.6"
    container_name: "postgres-youtube-test"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=youtube-test
    ports:
      - "5433:5432"
